default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: angular2_development

test: &test
  <<: *default
  database: angular2_test

production:
  <<: *default
  database: angular2_development